language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.0
 - 7.1

matrix:
 exclude:
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
      php: 7.0
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
      php: 7.0
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
      php: 7.1
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
      php: 7.1
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
      php: 7.1
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
      php: 7.1
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
      php: 7.1
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
      php: 7.1
 allow_failures:
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
      php: 5.6
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE 
      php: 5.6
    - env: DB=pgsql MOODLE_BRANCH=master
    - env: DB=mysqli MOODLE_BRANCH=master


env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  #- moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  #- moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit

  - >
    if [ "$MOODLE_BRANCH" \> 'MOODLE_30_STABLE' ];
      then
          moodle-plugin-ci behat
      fi

