language: php

sudo: required
dist: precise

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

addons:
  postgresql: "9.3"

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
 exclude:
    - env: DB=pgsql MOODLE_BRANCH=master
      php: 5.6
    - env: DB=mysqli MOODLE_BRANCH=master
      php: 5.6
 allow_failures:
    - env: DB=pgsql MOODLE_BRANCH=master
    - env: DB=mysqli MOODLE_BRANCH=master
 fast_finish: true


env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

jobs:
  include:
    # Prechecks against latest Moodle stable only.
    - stage: static
      php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
      script:
      - moodle-plugin-ci phplint
      # - moodle-plugin-ci phpcpd
      - moodle-plugin-ci phpmd
      # - moodle-plugin-ci codechecker
      - moodle-plugin-ci savepoints
      # - moodle-plugin-ci mustache
      - moodle-plugin-ci grunt
      - moodle-plugin-ci validate

    # Smaller build matrix for development builds
    - stage: develop
      php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
      script:
      - moodle-plugin-ci phpunit --coverage-clover
      - moodle-plugin-ci behat

# Unit tests and behat tests against full matrix.
script:
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat
after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - static
  - name: develop
    if: branch != master AND (type != pull_request OR head_branch != master) AND (tag IS blank)
  - name: test
    if: branch = master OR (type = pull_request AND head_branch = master) OR (tag IS present)
